作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [20]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
try:
    array1_inv = np.linalg.inv(array1)
except np.linalg.LinAlgError:
    print('cannot inv')
ans_1 = np.dot(array1, array1_inv)

ans_1

array([[1., 0.],
       [0., 1.]])

In [26]:
#2. 運用上列array計算特徵值、特徵向量?
e_vals, e_ecvs = np.linalg.eig(array1)
e_vals


array([13.,  2.])

In [25]:
e_ecvs

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [4]:
#3. 運用上列array計算SVD?

In [27]:
np.linalg.matrix_rank(array1)

2